-- OPERO reset + seed for an existing tenant.
-- Keeps users and tenant records, then fills feature tables with Indonesian data.
-- IDs are generated by PostgreSQL, not hardcoded seed IDs.

BEGIN;

TRUNCATE TABLE
  "chat_reads",
  "chat_message",
  "chat_channel",
  "content_post",
  "social_channel",
  "document",
  "folder",
  "asset",
  "product",
  "transaction",
  "invoice",
  "sale",
  "goal",
  "role",
  "contact",
  "task",
  "campaign",
  "flow",
  "tenant_activity",
  "user_presence"
RESTART IDENTITY CASCADE;

WITH selected_tenant AS (
  SELECT id
  FROM "organization"
  ORDER BY
    CASE WHEN status = 'active' THEN 0 ELSE 1 END,
    "createdAt" ASC
  LIMIT 1
),
tenant_user AS (
  SELECT m."organizationId", m."userId"
  FROM "member" m
  JOIN selected_tenant t ON t.id = m."organizationId"
  ORDER BY
    CASE WHEN m.role = 'owner' THEN 0 WHEN m.role = 'admin' THEN 1 ELSE 2 END,
    m."createdAt" ASC
  LIMIT 1
),
seed_role AS (
  INSERT INTO "role" (
    id, "organizationId", title, name, description, status, permissions,
    color, "sortOrder", "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    role_name,
    role_name,
    'Role operasional untuk tim ' || role_name || '.',
    CASE WHEN i % 6 = 0 THEN 'Inactive' ELSE 'Active' END,
    permissions,
    color,
    i,
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT *
    FROM (VALUES
      (1, 'Owner Operasional', '["tenant.manage","finance.manage","reports.view"]'::jsonb, '#2563eb'),
      (2, 'Manajer Marketing', '["campaigns.manage","content.manage","social.manage"]'::jsonb, '#16a34a'),
      (3, 'Manajer Sales', '["sales.manage","invoices.manage","contacts.view"]'::jsonb, '#dc2626'),
      (4, 'Finance Officer', '["finance.manage","invoices.manage"]'::jsonb, '#9333ea'),
      (5, 'Content Strategist', '["content.manage","campaigns.view"]'::jsonb, '#ea580c'),
      (6, 'Admin Dokumen', '["documents.manage","assets.view"]'::jsonb, '#0891b2'),
      (7, 'Asset Controller', '["assets.manage"]'::jsonb, '#4f46e5'),
      (8, 'Customer Success', '["contacts.manage","sales.view"]'::jsonb, '#0f766e'),
      (9, 'Project Lead', '["tasks.manage","flows.manage","goals.manage"]'::jsonb, '#7c3aed'),
      (10, 'Staff Produksi', '["tasks.view","assets.view"]'::jsonb, '#ca8a04')
    ) AS base(i, role_name, permissions, color)
    UNION ALL
    SELECT g, 'Staff Operasional ' || g, '["tasks.view","documents.view"]'::jsonb, '#64748b'
    FROM generate_series(11, 20) g
  ) roles
  RETURNING id, "organizationId", "sortOrder"
),
seed_contact AS (
  INSERT INTO "contact" (
    id, "organizationId", title, name, "relationshipType", status, industry,
    description, persons, tags, "assignedStaff", notes, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    company_name,
    company_name,
    CASE WHEN i % 4 = 0 THEN 'Vendor' WHEN i % 3 = 0 THEN 'Partner' ELSE 'Client' END,
    CASE WHEN i % 7 = 0 THEN 'Prospect' ELSE 'Active' END,
    industry,
    'Kontak bisnis area ' || city || ' untuk kebutuhan operasional dan campaign.',
    jsonb_build_array(jsonb_build_object(
      'id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
      'name', person_name,
      'email', lower(replace(person_name, ' ', '.')) || '@contoh.co.id',
      'phone', '+62812' || lpad((11000000 + i)::text, 8, '0'),
      'role', 'PIC',
      'isPrimary', true
    )),
    jsonb_build_array(lower(industry), lower(city), CASE WHEN i % 2 = 0 THEN 'prioritas' ELSE 'regular' END),
    jsonb_build_array('Tim ' || CASE WHEN i % 2 = 0 THEN 'Sales' ELSE 'Marketing' END),
    'Follow up berkala untuk kebutuhan ' || industry || '.',
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY['Kopi Sari Makmur','Batik Nusantara Jaya','Rasa Dapur Indonesia','Sinar Laut Logistik','Kriya Lokal Mandiri','Bumi Herbal Sehat','Surya Tekno Abadi','Pangan Kita Sentosa','Studio Visual Jakarta','Mitra Retail Bandung','Toko Bahagia Surabaya','Kreasi Kayu Jepara','Klinik Prima Sehat','Ruang Belajar Cerdas','Travel Kita Bali','Agrikultur Lestari','Percetakan Merdeka','Eventika Nusantara','Karya Digital Solo','Sentra UMKM Medan'])[g],
      (ARRAY['Dewi Lestari','Bima Pratama','Sari Wulandari','Rizky Saputra','Nadia Kirana','Arif Nugroho','Maya Oktavia','Fajar Ramadhan','Intan Permata','Agus Santoso','Putri Maharani','Yoga Firmansyah','Ratna Dewanti','Bagus Wijaya','Citra Anggraini','Hendra Gunawan','Lina Marlina','Dimas Aditya','Ayu Saraswati','Raka Mahendra'])[g],
      (ARRAY['F&B','Fashion','Kuliner','Logistik','Kerajinan','Kesehatan','Teknologi','Retail','Creative Studio','Retail','Retail','Furniture','Healthcare','Education','Travel','Agriculture','Printing','Event','Digital Agency','UMKM'])[g],
      (ARRAY['Jakarta','Yogyakarta','Bandung','Semarang','Solo','Surabaya','Tangerang','Depok','Jakarta','Bandung','Surabaya','Jepara','Bekasi','Malang','Denpasar','Bogor','Medan','Jakarta','Solo','Medan'])[g]
    FROM generate_series(1, 20) g
  ) data(i, company_name, person_name, industry, city)
  RETURNING id, "organizationId", name
),
seed_campaign AS (
  INSERT INTO "campaign" (
    id, "organizationId", title, name, objective, description, status, priority,
    "startDate", "endDate", budget, currency, tags, "assignedStaff",
    activities, attachments, notes, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    campaign_name,
    campaign_name,
    objective,
    'Campaign terstruktur untuk pasar Indonesia dengan channel digital dan offline.',
    (ARRAY['Planning','Active','Active','Paused','Completed'])[1 + (i % 5)],
    (ARRAY['Low','Medium','High','Urgent'])[1 + (i % 4)],
    NOW() - (i || ' days')::interval,
    NOW() + ((14 + i) || ' days')::interval,
    15000000 + (i * 1750000),
    'IDR',
    jsonb_build_array('Indonesia', channel, objective_tag),
    jsonb_build_array('Tim Marketing', 'Tim Konten'),
    '[]'::jsonb,
    '[]'::jsonb,
    'Pantau performa mingguan dan update brief sesuai insight.',
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY['Campaign Ramadan Kopi Sari','Peluncuran Batik Motif Baru','Promo Bundling Dapur Nusantara','Brand Awareness Logistik UMKM','Katalog Kriya Lokal','Edukasi Herbal Sehat','Webinar Transformasi Digital','Promo Akhir Bulan Retail','Portfolio Studio Visual','Program Loyalti Bandung','Diskon Weekend Surabaya','Pameran Kayu Jepara','Kampanye Klinik Prima','Open Class Ruang Belajar','Travel Fair Bali','Panen Raya Lestari','Promo Cetak Merdeka','Roadshow Eventika','Lead Gen Digital Solo','Festival UMKM Medan'])[g],
      (ARRAY['Instagram','TikTok','Marketplace','LinkedIn','Website'])[1 + (g % 5)],
      (ARRAY['Awareness','Revenue','Lead Generation','Retention'])[1 + (g % 4)],
      (ARRAY['Naikkan awareness','Dorong penjualan','Tambah leads berkualitas','Aktivasi pelanggan lama'])[1 + (g % 4)]
    FROM generate_series(1, 20) g
  ) data(i, campaign_name, channel, objective_tag, objective)
  RETURNING id, "organizationId", name
),
seed_flow AS (
  INSERT INTO "flow" (
    id, "organizationId", title, name, category, description, status,
    progress, stages, notes, "dueDate", "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    flow_name,
    flow_name,
    (ARRAY['Operations','Marketing','Sales','Finance'])[1 + (i % 4)],
    flow_desc,
    (ARRAY['Active','Active','Draft','Completed'])[1 + (i % 4)],
    LEAST(95, 10 + (i * 4)),
    jsonb_build_array(
      jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'name', 'Brief', 'isCompleted', i > 4, 'order', 0, 'checklist', jsonb_build_array(jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'text', 'Kumpulkan kebutuhan', 'isCompleted', i > 4))),
      jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'name', 'Produksi', 'isCompleted', i > 10, 'order', 1, 'checklist', jsonb_build_array(jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'text', 'Eksekusi pekerjaan utama', 'isCompleted', i > 10), jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'text', 'Quality check', 'isCompleted', i > 12))),
      jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'name', 'Approval', 'isCompleted', i > 16, 'order', 2, 'checklist', jsonb_build_array(jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'text', 'Kirim approval final', 'isCompleted', i > 16)))
    ),
    jsonb_build_array(jsonb_build_object(
      'id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
      'text', flow_note,
      'timestamp', NOW(),
      'user', jsonb_build_object('id', u."userId", 'name', 'Owner Tenant')
    )),
    NOW() + ((7 + i) || ' days')::interval,
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY['Produksi Konten Campaign Ramadan','Approval Desain Katalog Batik','Pemenuhan Pesanan Hampers','Onboarding Vendor Logistik','Review Legal Kerja Sama','Pengadaan Aset Studio','Publikasi Kalender Konten','Rekonsiliasi Invoice Bulanan','Follow Up Lead Marketplace','Quality Control Dokumen','Produksi Foto Produk','Persiapan Webinar UMKM','Retensi Pelanggan Prioritas','Audit Stok Gudang','Distribusi Materi Promosi','Approval Promo Akhir Bulan','Penjadwalan Social Media','Proses Klaim Garansi Aset','Pembuatan Laporan Keuangan','Closing Campaign Kuartalan'])[g],
      (ARRAY['Alur brief, produksi, dan approval konten Ramadan.','Alur review motif, copy, dan katalog final.','Alur konfirmasi stok sampai pengiriman hampers.','Alur verifikasi vendor pengiriman baru.','Alur pemeriksaan kontrak dan dokumen kerja sama.','Alur pembelian, penerimaan, dan pencatatan aset studio.','Alur penyusunan konten sosial mingguan.','Alur cocokkan invoice, transaksi, dan bukti bayar.','Alur follow up prospek dari marketplace.','Alur pemeriksaan kelengkapan file dokumen.','Alur booking studio sampai delivery aset visual.','Alur registrasi, materi, dan reminder webinar.','Alur penanganan akun pelanggan prioritas.','Alur hitung stok dan tindak lanjut low stock.','Alur distribusi materi ke tim sales dan channel sosial.','Alur validasi diskon dan approval campaign.','Alur drafting, schedule, dan publish konten.','Alur pencatatan aset rusak sampai garansi.','Alur rekap pemasukan, pengeluaran, dan laporan.','Alur evaluasi KPI campaign dan arsip final.'])[g],
      (ARRAY['Pastikan brief disetujui sebelum produksi.','Katalog final dikunci H-3 publish.','Cek stok sebelum invoice dikirim.','Simpan NPWP dan rekening vendor.','Tunggu review owner sebelum tanda tangan.','Foto serial number saat barang datang.','Gunakan jam posting sesuai performa channel.','Lampirkan bukti bayar setiap invoice.','Follow up maksimal 1x24 jam.','File wajib punya nama dan folder benar.','Preview dikirim sebelum invoice produksi.','Materi final maksimal H-2 webinar.','Catat semua komplain di notes kontak.','Laporkan item di bawah threshold.','Gunakan versi materi terbaru.','Diskon tidak boleh lewat margin minimal.','Caption wajib dicek sebelum dijadwalkan.','Cek masa garansi sebelum servis mandiri.','Pisahkan income dan expense manual.','Arsipkan aset dan laporan campaign.'])[g]
    FROM generate_series(1, 20) g
  ) data(i, flow_name, flow_desc, flow_note)
  RETURNING id, "organizationId"
),
seed_goal AS (
  INSERT INTO "goal" (
    id, "organizationId", title, "targetOutcome", description, status, priority,
    metric, "targetValue", "currentValue", progress, "startDate", "dueDate",
    tags, activities, notes, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    goal_name,
    goal_outcome,
    goal_desc,
    (ARRAY['on-track','at-risk','completed','behind'])[1 + (i % 4)],
    (ARRAY['Low','Medium','High'])[1 + (i % 3)],
    (ARRAY['Revenue','Leads','Tasks','Engagement'])[1 + (i % 4)],
    10000000 + (i * 5000000),
    i * 1800000,
    LEAST(100, i * 5),
    NOW() - (i || ' days')::interval,
    NOW() + ((20 + i) || ' days')::interval,
    jsonb_build_array('target', 'q' || ((i % 4) + 1)),
    '[]'::jsonb,
    'Review progress setiap pekan.',
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY['Naikkan Omzet Campaign Ramadan','Tambah Lead Marketplace Berkualitas','Turunkan Piutang Lewat Invoice Tepat Waktu','Percepat SLA Produksi Konten','Tingkatkan Engagement Instagram','Rapikan Arsip Dokumen Campaign','Jaga Stok Produk Prioritas','Optimalkan Biaya Produksi','Tambah Repeat Order Klien Retainer','Percepat Approval Internal','Naikkan Konversi Promo Akhir Bulan','Lengkapi Data Kontak Strategis','Perbaiki Utilisasi Aset Studio','Tingkatkan Reach TikTok','Selesaikan Audit Keuangan Bulanan','Kurangi Task Overdue','Naikkan Nilai Penjualan Produk Premium','Perkuat Kolaborasi Partner Lokal','Selesaikan Onboarding Vendor','Tutup Campaign Kuartal Tanpa Blocking'])[g],
      (ARRAY['Omzet campaign mencapai minimal Rp75.000.000.','Mendapat 120 lead valid dari marketplace.','90% invoice terkirim maksimal H+1 setelah sale.','Konten selesai maksimal 3 hari setelah brief.','Engagement rate naik minimal 4%.','Semua dokumen campaign masuk folder benar.','Stok produk prioritas aman di atas threshold.','Biaya produksi turun 10% tanpa menurunkan kualitas.','Repeat order dari klien retainer naik 20%.','Approval internal selesai maksimal 2 hari kerja.','Konversi promo naik minimal 15%.','Data 50 kontak prioritas lengkap dan terverifikasi.','Aset studio terpakai minimal 70% tiap bulan.','Reach TikTok naik sampai 250.000 per bulan.','Laporan keuangan bulanan selesai sebelum tanggal 5.','Task overdue turun di bawah 5 item.','Penjualan produk premium naik 25%.','Minimal 5 partner lokal aktif dalam campaign.','Semua vendor baru lolos verifikasi dokumen.','Campaign kuartal ditutup dengan laporan final.'])[g],
      (ARRAY['Fokus pada paket hampers dan bundling.','Kualifikasi lead memakai status kontak.','Prioritaskan invoice dari sale confirmed.','Pantau flow produksi setiap hari.','Optimalkan Reels dan carousel edukasi.','Gunakan folder campaign dan tag dokumen.','Pantau low stock dari modul produk.','Bandingkan biaya produksi per campaign.','Gunakan catatan kontak untuk follow up.','Gunakan flow approval yang sudah disepakati.','Tes beberapa channel dan jam posting.','Lengkapi PIC, email, telepon, dan industry.','Cek asset in use dan maintenance.','Prioritaskan konten video pendek.','Cocokkan transaction dengan invoice.','Review task yang melewati due date.','Dorong upsell varian premium.','Buat daftar partner berdasarkan kota.','Simpan dokumen legal vendor di folder.','Pastikan semua laporan dan aset diarsipkan.'])[g]
    FROM generate_series(1, 20) g
  ) data(i, goal_name, goal_outcome, goal_desc)
  RETURNING id, "organizationId"
),
seed_product AS (
  INSERT INTO "product" (
    id, "organizationId", title, name, sku, category, type, price, currency,
    stock, "totalQuantity", "minThreshold", status, description, variants,
    activities, notes, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    product_name,
    product_name,
    'SKU-ID-' || lpad(i::text, 4, '0'),
    category,
    CASE WHEN i % 5 = 0 THEN 'Service' ELSE 'Physical' END,
    50000 + (i * 27500),
    'IDR',
    20 + (i * 8),
    20 + (i * 8),
    10,
    CASE WHEN i % 6 = 0 THEN 'Low Stock' ELSE 'In Stock' END,
    'Produk atau paket layanan untuk pasar Indonesia.',
    jsonb_build_array(
      jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'name', 'Reguler', 'sku', 'SKU-ID-' || lpad(i::text, 4, '0') || '-REG', 'price', 50000 + (i * 27500), 'quantity', 10 + (i * 4)),
      jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'name', 'Premium', 'sku', 'SKU-ID-' || lpad(i::text, 4, '0') || '-PRE', 'price', 75000 + (i * 32500), 'quantity', 10 + (i * 4))
    ),
    '[]'::jsonb,
    'Pastikan stok dan harga dicek sebelum campaign.',
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY['Hampers Kopi Premium','Kemeja Batik Lengan Panjang','Paket Sambal Nusantara','Jasa Pengiriman UMKM','Tas Anyaman Lokal','Paket Herbal Imun','Audit Website UMKM','Rak Display Toko','Foto Produk Studio','Voucher Belanja Bandung','Paket Snack Surabaya','Meja Kayu Minimalis','Paket Medical Checkup','Kelas Bahasa Inggris','Paket Wisata Bali','Beras Organik Lestari','Cetak Banner Promosi','Paket Event Gathering','Jasa Iklan Digital','Paket UMKM Starter'])[g],
      (ARRAY['Hampers','Fashion','Kuliner','Logistik','Kerajinan','Kesehatan','Teknologi','Retail','Creative','Voucher','F&B','Furniture','Healthcare','Education','Travel','Agriculture','Printing','Event','Digital','UMKM'])[g]
    FROM generate_series(1, 20) g
  ) data(i, product_name, category)
  RETURNING id, "organizationId", name, price
),
seed_task AS (
  INSERT INTO "task" (
    id, "organizationId", title, description, status, priority, "dueDate",
    "campaignId", labels, assignees, checklist, comments, activity, attachments,
    "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    c."organizationId",
    task_title,
    task_desc,
    (ARRAY['Todo','In Progress','Review','Done'])[1 + (i % 4)],
    (ARRAY['Low','Medium','High','Urgent'])[1 + (i % 4)],
    NOW() + ((2 + i) || ' days')::interval,
    c.id,
    jsonb_build_array('Campaign', task_label),
    '[]'::jsonb,
    jsonb_build_array(jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'text', checklist_text, 'done', i % 3 = 0)),
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM (
    SELECT c.*, row_number() OVER (ORDER BY c.name) AS i
    FROM seed_campaign c
  ) c
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      (ARRAY['Finalisasi brief visual campaign','Validasi promo dan margin produk','Buat caption Instagram Reels','Siapkan daftar kontak prioritas','Review invoice sebelum dikirim','Update stok produk promo','Upload dokumen kontrak vendor','Cek aset kamera studio','Susun jadwal konten mingguan','Follow up pembayaran klien','Rekap performa social channel','Buat materi webinar UMKM','Konfirmasi alamat pengiriman','Audit folder dokumen campaign','Input transaksi biaya produksi','Review desain katalog final','Siapkan laporan campaign','Cek approval owner','Buat daftar partner lokal','Arsipkan aset campaign selesai'])[c.i],
      (ARRAY['Pastikan visual sesuai guideline brand dan objective campaign.','Hitung ulang diskon, pajak, dan total sebelum publish promo.','Caption harus punya hook, CTA, dan hashtag lokal.','Lengkapi PIC, email, dan nomor WhatsApp kontak.','Cek recipient, due date, dan item invoice.','Pastikan stok tidak turun di bawah minimum threshold.','Simpan kontrak vendor ke folder yang sesuai.','Pastikan kamera dan lampu siap sebelum produksi.','Jadwalkan post berdasarkan kalender campaign.','Kirim reminder sopan sesuai status invoice.','Bandingkan followers, reach, views, dan interaction.','Siapkan slide, rundown, dan form registrasi.','Cek alamat dan catatan pengiriman sale.','Rapikan naming file dan tag dokumen.','Catat expense produksi dengan bukti bayar.','Kunci desain setelah revisi terakhir disetujui.','Gabungkan data sale, invoice, dan social channel.','Pastikan semua approval tertulis di notes.','Prioritaskan partner berdasarkan kota dan industri.','Pindahkan dokumen final ke folder arsip.'])[c.i],
      (ARRAY['Brief','Pricing','Content','Contacts','Invoice','Stock','Legal','Asset','Schedule','Payment','Analytics','Webinar','Delivery','Documents','Finance','Design','Report','Approval','Partner','Archive'])[c.i],
      (ARRAY['Review brief klien','Cek angka dan pajak','Tulis caption final','Validasi data PIC','Cek detail invoice','Cek stok tersedia','Upload file kontrak','Tes aset produksi','Atur tanggal publish','Kirim follow up','Ambil data performa','Finalisasi materi','Konfirmasi alamat','Rapikan folder','Upload bukti biaya','Export desain final','Susun rangkuman','Minta approval','Hubungi partner','Arsipkan file final'])[c.i]
  ) task_data(task_title, task_desc, task_label, checklist_text)
  RETURNING id
),
campaign_tasks AS (
  SELECT c.id, c."organizationId", row_number() OVER (ORDER BY c.name) AS i
  FROM seed_campaign c
),
seed_sale AS (
  INSERT INTO "sale" (
    id, "organizationId", "saleNumber", title, status, "saleType", "paymentStatus",
    "customerName", "recipientName", "contactName", "contactId", items, subtotal,
    "discountAmount", "taxAmount", "grandTotal", currency, notes, activities,
    attachments, "shippingAddress", "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    c."organizationId",
    'SO-2026-' || lpad(c.i::text, 4, '0'),
    'Penjualan ' || p.name,
    CASE WHEN c.i % 5 = 0 THEN 'Draft' WHEN c.i % 4 = 0 THEN 'Completed' ELSE 'Confirmed' END,
    'Product Sale',
    CASE WHEN c.i % 3 = 0 THEN 'Paid' ELSE 'Unpaid' END,
    c.name,
    c.name,
    c.name,
    c.id,
    jsonb_build_array(jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'name', p.name, 'quantity', 1 + (c.i % 5), 'price', p.price, 'subtotal', (1 + (c.i % 5)) * p.price)),
    (1 + (c.i % 5)) * p.price,
    0,
    ((1 + (c.i % 5)) * p.price) * 0.11,
    ((1 + (c.i % 5)) * p.price) * 1.11,
    'IDR',
    'Penjualan seeded untuk data demo tenant.',
    '[]'::jsonb,
    '[]'::jsonb,
    sale_address,
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM (
    SELECT id, "organizationId", name, row_number() OVER (ORDER BY name) AS i FROM seed_contact
  ) c
  JOIN (
    SELECT id, name, price, row_number() OVER (ORDER BY name) AS i FROM seed_product
  ) p ON p.i = c.i
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT (ARRAY[
      'Jl. Kemang Raya No. 12, Jakarta Selatan',
      'Jl. Malioboro No. 88, Yogyakarta',
      'Jl. Asia Afrika No. 45, Bandung',
      'Kawasan Industri Candi Blok D-7, Semarang',
      'Jl. Slamet Riyadi No. 210, Solo',
      'Jl. Basuki Rahmat No. 17, Surabaya',
      'Ruko BSD Sektor 1.2 Blok C5, Tangerang Selatan',
      'Jl. Margonda Raya No. 55, Depok',
      'Jl. Wolter Monginsidi No. 31, Jakarta Selatan',
      'Jl. Braga No. 22, Bandung',
      'Jl. Tunjungan No. 19, Surabaya',
      'Jl. Pemuda No. 144, Jepara',
      'Jl. Ahmad Yani No. 62, Bekasi',
      'Jl. Ijen No. 9, Malang',
      'Jl. Sunset Road No. 101, Denpasar',
      'Jl. Pajajaran No. 70, Bogor',
      'Jl. Gatot Subroto No. 8, Medan',
      'Jl. Senopati No. 28, Jakarta Selatan',
      'Jl. Adi Sucipto No. 16, Solo',
      'Jl. Sisingamangaraja No. 40, Medan'
    ])[c.i]
  ) sale_data(sale_address)
  RETURNING id, "organizationId", "saleNumber"
),
seed_invoice AS (
  INSERT INTO "invoice" (
    id, "organizationId", "invoiceNumber", title, status, "recipientName",
    "recipientEmail", "issueDate", "dueDate", items, subtotal, "discountAmount",
    "taxRate", "taxAmount", "totalAmount", currency,
    "paymentStatus", "paymentMethod", "saleId", notes, activities, attachments,
    "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    s."organizationId",
    'INV/OPERO/2026/' || lpad(s.i::text, 4, '0'),
    'Invoice ' || s."saleNumber",
    CASE WHEN s.i % 4 = 0 THEN 'Paid' ELSE 'Unpaid' END,
    c.name,
    lower(replace(c.name, ' ', '.')) || '@contoh.co.id',
    NOW() - (s.i || ' days')::interval,
    NOW() + ((14 + s.i) || ' days')::interval,
    jsonb_build_array(jsonb_build_object('id', ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)), 'description', 'Tagihan penjualan ' || s.i, 'quantity', 1, 'unitPrice', total_amount, 'amount', total_amount)),
    total_amount / 1.11,
    0,
    11,
    total_amount - (total_amount / 1.11),
    total_amount,
    'IDR',
    CASE WHEN s.i % 4 = 0 THEN 'Paid' ELSE 'Unpaid' END,
    CASE WHEN s.i % 2 = 0 THEN 'Bank Transfer' ELSE 'QRIS' END,
    s.id,
    invoice_note,
    '[]'::jsonb,
    '[]'::jsonb,
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM (
    SELECT id, "organizationId", "saleNumber", row_number() OVER (ORDER BY "saleNumber") AS i, 1000000 + (row_number() OVER (ORDER BY "saleNumber") * 275000) AS total_amount FROM seed_sale
  ) s
  JOIN (
    SELECT id, name, row_number() OVER (ORDER BY name) AS i FROM seed_contact
  ) c ON c.i = s.i
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT (ARRAY[
      'Termin pembayaran 14 hari setelah invoice diterima.',
      'Pembayaran melalui transfer bank sebelum pengiriman tahap kedua.',
      'Mohon cantumkan nomor invoice pada berita transfer.',
      'Invoice mencakup biaya produksi dan distribusi campaign.',
      'Tagihan retainer bulanan sesuai kontrak kerja sama.',
      'Pembayaran dapat dilakukan via QRIS untuk nominal kecil.',
      'Follow up finance dijadwalkan tiga hari sebelum due date.',
      'Invoice ini terkait campaign marketplace dan social media.',
      'Pajak dihitung berdasarkan nilai transaksi yang disepakati.',
      'Bukti bayar dikirim ke finance setelah transfer berhasil.',
      'Tagihan untuk paket layanan prioritas bulan berjalan.',
      'Pengiriman final dilakukan setelah pembayaran terverifikasi.',
      'Invoice disiapkan berdasarkan sale order yang sudah confirmed.',
      'Keterlambatan pembayaran akan masuk daftar follow up finance.',
      'Dokumen pendukung tersedia di folder campaign terkait.',
      'Pembayaran sebagian wajib dikonfirmasi sebelum produksi.',
      'Nominal sudah termasuk pajak dan biaya administrasi.',
      'Harap hubungi finance bila membutuhkan faktur pajak.',
      'Invoice ini digunakan untuk rekonsiliasi laporan bulanan.',
      'Status pembayaran diperbarui setelah mutasi bank cocok.'
    ])[s.i]
  ) invoice_data(invoice_note)
  RETURNING id
),
seed_transaction AS (
  INSERT INTO "transaction" (
    id, "organizationId", type, title, amount, currency, category,
    "transactionDate", "paymentMethod", reference, "sourceType", status,
    "contactName", notes, activities, attachments, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    (ARRAY['Income','Expense','Refund'])[1 + (i % 3)],
    transaction_title,
    250000 + (i * 125000),
    'IDR',
    (ARRAY['Sales','Marketing Production','Operational','Refund'])[1 + (i % 4)],
    NOW() - (i || ' days')::interval,
    CASE WHEN i % 2 = 0 THEN 'Bank Transfer' ELSE 'QRIS' END,
    'TRX-2026-' || lpad(i::text, 4, '0'),
    CASE WHEN i % 2 = 0 THEN 'Invoice' ELSE 'Manual' END,
    CASE WHEN i % 5 = 0 THEN 'Pending' ELSE 'Completed' END,
    contact_name,
    transaction_note,
    '[]'::jsonb,
    '[]'::jsonb,
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY[
        'Pembayaran DP Hampers Ramadan',
        'Biaya Sewa Studio Foto Produk',
        'Refund Selisih Ongkir Surabaya',
        'Pembayaran Invoice Retainer Batik',
        'Pembelian Properti Konten Reels',
        'Biaya Iklan TikTok Awareness',
        'Pembayaran Pelunasan Event Gathering',
        'Biaya Cetak Banner Promo',
        'Refund Pembatalan Kelas Online',
        'Pembelian Hard Disk Backup',
        'Pembayaran Campaign Marketplace',
        'Biaya Transport Produksi Bandung',
        'Pembayaran Paket Medical Checkup',
        'Biaya Vendor Desain Katalog',
        'Refund Produk Rusak Pengiriman',
        'Pembayaran Travel Fair Bali',
        'Biaya Konsumsi Webinar UMKM',
        'Pembelian Lampu Studio LED',
        'Pembayaran Jasa Iklan Digital',
        'Biaya Kurir Dokumen Legal'
      ])[g],
      (ARRAY[
        'Kopi Sari Makmur',
        'Studio Visual Jakarta',
        'Toko Bahagia Surabaya',
        'Batik Nusantara Jaya',
        'Kriya Lokal Mandiri',
        'Surya Tekno Abadi',
        'Eventika Nusantara',
        'Percetakan Merdeka',
        'Ruang Belajar Cerdas',
        'Gudang Operasional',
        'Mitra Retail Bandung',
        'Tim Produksi Bandung',
        'Klinik Prima Sehat',
        'Vendor Desain Lokal',
        'Pangan Kita Sentosa',
        'Travel Kita Bali',
        'Komunitas UMKM',
        'Jakarta Camera Center',
        'Karya Digital Solo',
        'Kurir Internal'
      ])[g],
      (ARRAY[
        'Masuk dari pembayaran awal sale order hampers.',
        'Expense untuk produksi foto katalog bulanan.',
        'Refund karena ongkir aktual lebih rendah.',
        'Income dari kontrak retainer fashion.',
        'Properti dipakai untuk konten campaign Ramadan.',
        'Budget iklan untuk target reach TikTok.',
        'Pelunasan event setelah laporan disetujui.',
        'Biaya produksi materi offline campaign.',
        'Refund peserta yang membatalkan sebelum kelas.',
        'Aset penyimpanan untuk arsip video.',
        'Income campaign dari kanal marketplace.',
        'Transport tim untuk produksi konten onsite.',
        'Income paket layanan kesehatan korporat.',
        'Biaya eksternal untuk finalisasi katalog.',
        'Refund disetujui setelah QC produk selesai.',
        'Income aktivasi travel fair bulan ini.',
        'Expense operasional acara webinar.',
        'Pembelian aset pendukung studio.',
        'Income layanan iklan performa.',
        'Expense pengiriman dokumen kontrak vendor.'
      ])[g]
    FROM generate_series(1, 20) g
  ) transaction_data(i, transaction_title, contact_name, transaction_note)
  RETURNING id
),
seed_asset AS (
  INSERT INTO "asset" (
    id, "organizationId", title, name, category, "assetCode", quantity, status,
    "assignedTo", location, "purchaseDate", "purchaseValue", currency, "supplierName",
    activities, comments, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    asset_name,
    asset_name,
    category,
    'AST-OPR-' || lpad(i::text, 4, '0'),
    1 + (i % 4),
    CASE WHEN i % 6 = 0 THEN 'Maintenance' ELSE 'In Use' END,
    jsonb_build_array('Tim ' || (ARRAY['Konten','Sales','Finance','Operasional'])[1 + (i % 4)]),
    (ARRAY['Jakarta','Bandung','Surabaya','Yogyakarta'])[1 + (i % 4)],
    NOW() - ((30 + i) || ' days')::interval,
    750000 + (i * 350000),
    'IDR',
    'Supplier Lokal ' || i,
    '[]'::jsonb,
    '[]'::jsonb,
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY['Kamera Sony A6400','Laptop Lenovo ThinkPad','Tripod Video','Lampu Studio LED','Printer Label','Router Kantor','Meja Kerja','Kursi Ergonomis','Hard Disk Backup','Tablet Desain','Mikrofon Wireless','Backdrop Foto','Scanner Dokumen','Proyektor Meeting','Rak Arsip','Mesin Kopi Kantor','Kamera Canon M50','Monitor Ultrawide','UPS Server','Whiteboard Meeting'])[g],
      (ARRAY['Produksi','IT','Produksi','Produksi','Operasional','IT','Furniture','Furniture','IT','Creative','Produksi','Produksi','Dokumen','Meeting','Dokumen','Office','Produksi','IT','IT','Meeting'])[g]
    FROM generate_series(1, 20) g
  ) data(i, asset_name, category)
  RETURNING id
),
seed_folder AS (
  INSERT INTO "folder" (
    id, "organizationId", title, name, description, status, color,
    "sortOrder", tags, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    folder_name,
    folder_name,
    folder_desc,
    'Active',
    (ARRAY['#2563eb','#16a34a','#dc2626','#9333ea'])[1 + (i % 4)],
    i,
    jsonb_build_array('Dokumen', folder_tag),
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY[
        'Campaign Ramadan Kopi Sari',
        'Legal Vendor Logistik',
        'Invoice dan Pembayaran',
        'Materi Webinar UMKM',
        'Laporan Social Media',
        'Daftar Harga Produk',
        'SOP Produksi Studio',
        'Garansi dan Aset',
        'Template Konten',
        'Follow Up Klien Prioritas',
        'Audit Stok Gudang',
        'Travel Fair Bali',
        'MoU Partner Event',
        'Laporan Keuangan',
        'Brand Guideline Kriya',
        'Pengiriman dan Surat Jalan',
        'Open Class Education',
        'Desain Katalog Batik',
        'Legal Supplier Herbal',
        'Arsip Campaign Kuartal'
      ])[g],
      (ARRAY[
        'Folder untuk brief, aset, dan approval campaign Ramadan.',
        'Dokumen legal dan rekening vendor pengiriman.',
        'Invoice, bukti bayar, dan catatan rekonsiliasi.',
        'Proposal, rundown, dan materi presentasi webinar.',
        'Report reach, engagement, dan insight social channel.',
        'Price list produk yang dipakai sales dan finance.',
        'SOP produksi foto, video, dan quality control studio.',
        'Dokumen pembelian, serial number, dan klaim garansi aset.',
        'Template caption, visual, dan kalender konten.',
        'Catatan follow up dan dokumen klien prioritas.',
        'Dokumen hasil stock opname dan tindak lanjut stok rendah.',
        'Materi aktivasi dan laporan travel fair Bali.',
        'MoU, proposal, dan dokumentasi partner event.',
        'Laporan income, expense, refund, dan invoice bulanan.',
        'Panduan brand, logo, warna, dan tone komunikasi.',
        'Surat jalan dan bukti pengiriman pesanan.',
        'Rundown kelas, daftar peserta, dan materi pembelajaran.',
        'File desain katalog dan approval revisi batik.',
        'Legalitas supplier, kontrak, dan dokumen pendukung herbal.',
        'Arsip final campaign, laporan KPI, dan pembelajaran.'
      ])[g],
      (ARRAY['Campaign','Legal','Finance','Webinar','Social','Pricing','SOP','Asset','Template','Client','Stock','Travel','Partner','Report','Brand','Delivery','Education','Design','Supplier','Archive'])[g]
    FROM generate_series(1, 20) g
  ) folder_data(i, folder_name, folder_desc, folder_tag)
  RETURNING id, "organizationId", name
),
seed_document AS (
  INSERT INTO "document" (
    id, "organizationId", title, description, status, "fileName", "fileType",
    "fileSize", "storagePath", "fileUrl", "downloadUrl", "folderId", tags,
    "uploadedById", "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    f."organizationId",
    document_title,
    document_desc,
    CASE WHEN i % 5 = 0 THEN 'Archived' ELSE 'Active' END,
    document_slug || '.pdf',
    'pdf',
    100000 + (i * 4096),
    f."organizationId" || '/documents/' || document_slug || '.pdf',
    '/api/tenant/files?path=' || f."organizationId" || '/documents/' || document_slug || '.pdf',
    '/api/tenant/files?path=' || f."organizationId" || '/documents/' || document_slug || '.pdf',
    f.id,
    jsonb_build_array('Dokumen', 'Operasional'),
    u."userId",
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM (
    SELECT id, "organizationId", row_number() OVER (ORDER BY name) AS i FROM seed_folder
  ) f
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      (ARRAY['Brief Campaign Ramadan Kopi Sari','Kontrak Vendor Logistik Semarang','Invoice Retainer Batik Nusantara','Proposal Webinar UMKM Digital','Laporan Performa Instagram April','Daftar Harga Hampers Premium','SOP Produksi Foto Produk','Dokumen Garansi Kamera Studio','Template Caption Promo Bulanan','Rekap Pembayaran Klien Prioritas','Checklist Audit Stok Gudang','Materi Presentasi Travel Fair Bali','MoU Partner Eventika Nusantara','Laporan Keuangan Bulanan','Panduan Brand Kriya Lokal','Surat Jalan Pengiriman Hampers','Rundown Open Class Bahasa Inggris','Arsip Desain Katalog Batik','Dokumen Legal Supplier Herbal','Laporan Closing Campaign Kuartal'])[f.i],
      (ARRAY['Brief lengkap objective, target audiens, dan channel campaign.','Dokumen kerja sama vendor pengiriman untuk area Jawa Tengah.','Tagihan retainer untuk kebutuhan campaign fashion.','Proposal acara edukasi digital untuk UMKM lokal.','Ringkasan reach, followers, views, dan interaction Instagram.','Daftar harga produk hampers untuk sales dan invoice.','Standar kerja produksi visual di studio.','Bukti garansi dan serial number aset kamera.','Template caption yang dipakai tim konten.','Rekap status pembayaran dan follow up finance.','Checklist pemeriksaan stok produk prioritas.','Materi presentasi untuk aktivasi travel fair.','Dokumen kesepakatan kolaborasi partner event.','Ringkasan income, expense, dan refund bulanan.','Panduan warna, tone, dan pemakaian logo brand.','Dokumen pengiriman untuk pesanan hampers.','Rundown acara dan pembagian tugas kelas.','Arsip final desain katalog setelah approval.','Dokumen legal dan kontak supplier herbal.','Laporan final KPI dan pembelajaran campaign.'])[f.i],
      (ARRAY['brief-campaign-ramadan-kopi-sari','kontrak-vendor-logistik-semarang','invoice-retainer-batik-nusantara','proposal-webinar-umkm-digital','laporan-performa-instagram-april','daftar-harga-hampers-premium','sop-produksi-foto-produk','dokumen-garansi-kamera-studio','template-caption-promo-bulanan','rekap-pembayaran-klien-prioritas','checklist-audit-stok-gudang','materi-presentasi-travel-fair-bali','mou-partner-eventika-nusantara','laporan-keuangan-bulanan','panduan-brand-kriya-lokal','surat-jalan-pengiriman-hampers','rundown-open-class-bahasa-inggris','arsip-desain-katalog-batik','dokumen-legal-supplier-herbal','laporan-closing-campaign-kuartal'])[f.i]
  ) doc_data(document_title, document_desc, document_slug)
  RETURNING id
),
seed_social AS (
  INSERT INTO "social_channel" (
    id, "organizationId", title, platform, "accountName", handle,
    "profileUrl", status, followers, "postsThisMonth",
    interactions, "monthlyReach", "averageViews", notes, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    t.id,
    platform || ' ' || account_name,
    platform,
    account_name,
    '@' || lower(replace(account_name, ' ', '.')),
    'https://example.com/' || lower(replace(account_name, ' ', '-')),
    CASE WHEN i % 6 = 0 THEN 'Inactive' ELSE 'Active' END,
    1000 + (i * 1450),
    4 + (i % 18),
    300 + (i * 210),
    10000 + (i * 6500),
    500 + (i * 725),
    social_note,
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM selected_tenant t
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT
      g AS i,
      (ARRAY['Instagram','TikTok','YouTube','LinkedIn','Facebook'])[1 + (g % 5)],
      (ARRAY['Kopi Sari','Batik Nusantara','Dapur Indonesia','Logistik UMKM','Kriya Lokal','Herbal Sehat','Tekno Abadi','Pangan Kita','Studio Visual','Retail Bandung','Bahagia Surabaya','Kayu Jepara','Prima Sehat','Belajar Cerdas','Travel Bali','Agri Lestari','Cetak Merdeka','Eventika','Digital Solo','UMKM Medan'])[g],
      (ARRAY[
        'Channel utama untuk konten produk kopi dan hampers.',
        'Fokus konten edukasi motif batik dan styling kantor.',
        'Dipakai untuk promo resep, bundling, dan review pelanggan.',
        'Channel B2B untuk edukasi pengiriman UMKM.',
        'Konten storytelling pengrajin dan produk lokal.',
        'Channel edukasi kesehatan herbal dan testimoni.',
        'Dipakai untuk webinar dan tips transformasi digital.',
        'Channel promo retail, diskon, dan loyalty program.',
        'Portofolio visual untuk menarik klien produksi konten.',
        'Channel lokal untuk promo toko dan event Bandung.',
        'Konten promo weekend dan testimoni pelanggan Surabaya.',
        'Fokus pada proses produksi kayu dan katalog furniture.',
        'Channel edukasi layanan klinik dan reminder checkup.',
        'Dipakai untuk jadwal kelas dan materi belajar singkat.',
        'Channel destinasi, promo paket wisata, dan itinerary.',
        'Konten panen, edukasi organik, dan update petani.',
        'Channel promo cetak banner, brosur, dan kebutuhan event.',
        'Dokumentasi event, behind the scene, dan sponsor.',
        'Channel case study iklan dan insight performa digital.',
        'Publikasi acara, tenant UMKM, dan recap festival.'
      ])[g]
    FROM generate_series(1, 20) g
  ) data(i, platform, account_name, social_note)
  RETURNING id, "organizationId", title
),
seed_content AS (
  INSERT INTO "content_post" (
    id, "organizationId", title, status, "plannedDate", "plannedTime",
    "contentType", "targetAccountId", tags, "createdById", "updatedById", "createdAt", "updatedAt"
  )
  SELECT
    ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
    s."organizationId",
    content_title,
    (ARRAY['Planned','Draft','Scheduled','Published'])[1 + (i % 4)],
    NOW() + ((i % 14) || ' days')::interval,
    lpad((8 + (i % 10))::text, 2, '0') || ':00',
    (ARRAY['Reels','Carousel','Story','Short Video','Article'])[1 + (i % 5)],
    s.id,
    jsonb_build_array('Indonesia', 'Konten-' || i),
    u."userId",
    u."userId",
    NOW(),
    NOW()
  FROM (
    SELECT id, "organizationId", row_number() OVER (ORDER BY title) AS i FROM seed_social
  ) s
  CROSS JOIN tenant_user u
  CROSS JOIN LATERAL (
    SELECT (ARRAY['Reels Behind The Scene Produksi Hampers','Carousel Tips Pilih Batik Kantor','Story Promo Bundling Sambal','Short Video Packing Pesanan UMKM','Artikel LinkedIn Transformasi Digital','Reels Review Kriya Lokal','Carousel Edukasi Herbal Sehat','Story Flash Sale Retail Bandung','Video Portfolio Studio Visual','Post Testimoni Klien Surabaya','Reels Proses Kayu Jepara','Carousel Checklist Medical Checkup','Story Reminder Open Class','Short Video Destinasi Bali','Artikel Panen Raya Organik','Post Promo Cetak Banner','Reels Persiapan Event Gathering','Carousel Case Study Iklan Digital','Story Festival UMKM Medan','Post Closing Campaign Kuartal'])[s.i]
  ) content_data(content_title)
  RETURNING id
)
INSERT INTO "tenant_activity" (
  id, "organizationId", module, action, "entityType", "entityName", description, "userId", "createdAt"
)
SELECT
  ('c' || substr(md5(random()::text || clock_timestamp()::text), 1, 24)),
  t.id,
  'SYSTEM',
  'SEED',
  'Database',
  'Seed data Indonesia',
  'Database fitur diisi ulang dengan 20 data per modul utama.',
  u."userId",
  NOW()
FROM selected_tenant t
CROSS JOIN tenant_user u;

COMMIT;
